# Standalone file: do not edit by hand
# Generated by: pkgtools from @unit tags
# ----------------------------------------------------------------------
library(modelfitter)

# unit test start: .hux_substitute_fonts ----

test_that(".hux_substitute_fonts unit test", {

  # Automatically generated test case from roxygen @unit tag
  # Do not edit here - follow the link to the source file.
  # or navigate to topic with <F2>
  F2 = .hux_substitute_fonts
  

  testthat::expect_no_error(withCallingHandlers(
    {
      .hux_substitute_fonts(c("Roboto", "Arial", "Kings", "Unmatched"))
    },
    warning = function(e) {
      message("Warning issued: ", e$message)
      invokeRestart("muffleWarning")
    }
  ))

  # generates a failure if the overall test is failing with a link to the 
  # source of the unit test:
  testthat::expect(rlang::caller_env(n = 2)$ok,
    failure_message = "Source link for failing @unit test.",
    srcref = srcref(srcfile("../../R/huxtable-internals.R"), c(29, 1, 29+1, 1))
  )
})

# unit test end: .hux_substitute_fonts ----
# unit test start: .hux_default_layout ----

test_that(".hux_default_layout unit test", {

  # Automatically generated test case from roxygen @unit tag
  # Do not edit here - follow the link to the source file.
  # or navigate to topic with <F2>
  F2 = .hux_default_layout
  

  testthat::expect_no_error(withCallingHandlers(
    {
      hux <- iris %>% .hux_default_layout()
    },
    warning = function(e) {
      message("Warning issued: ", e$message)
      invokeRestart("muffleWarning")
    }
  ))

  # generates a failure if the overall test is failing with a link to the 
  # source of the unit test:
  testthat::expect(rlang::caller_env(n = 2)$ok,
    failure_message = "Source link for failing @unit test.",
    srcref = srcref(srcfile("../../R/huxtable-internals.R"), c(96, 1, 96+1, 1))
  )
})

# unit test end: .hux_default_layout ----
# end of unit tests ----
